// Copies the browser builds of Inkwell's rendering libraries into vendor/,
// so the app ships single files instead of whole npm packages.
// Run after updating any of them: npm run vendor
import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gemoji } from 'gemoji';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const nm = (p) => join(root, 'node_modules', p);
const out = (p) => join(root, 'vendor', p);

const copy = (from, to) => {
  mkdirSync(dirname(out(to)), { recursive: true });
  copyFileSync(nm(from), out(to));
};

copy('mermaid/dist/mermaid.min.js', 'mermaid.min.js');
copy('turndown/lib/turndown.browser.umd.js', 'turndown.js');
copy('turndown-plugin-gfm/dist/turndown-plugin-gfm.js', 'turndown-plugin-gfm.js');

// KaTeX: script, stylesheet and the woff2 fonts (Chromium never needs the woff/ttf fallbacks).
rmSync(out('katex'), { recursive: true, force: true });
copy('katex/dist/katex.min.js', 'katex/katex.min.js');
copy('katex/dist/katex.min.css', 'katex/katex.min.css');
for (const f of readdirSync(nm('katex/dist/fonts'))) {
  if (f.endsWith('.woff2')) copy(`katex/dist/fonts/${f}`, `katex/fonts/${f}`);
}

// Emoji shortcodes (:tada:) from GitHub's gemoji list.
const map = {};
for (const e of gemoji) for (const name of e.names) map[name] = e.emoji;
writeFileSync(out('emoji.js'), `// Generated by scripts/vendor.mjs from gemoji. Do not edit.\nwindow.INKWELL_EMOJI = ${JSON.stringify(map)};\n`);

console.log('vendor/ updated');
